<?php

function select_query($action){
    $result = Mage::getStoreConfig($action);
    return $result;
}
$gluu_oxd_id                = select_query('gluu/oxd/gluu_oxd_id');
$get_scopes                 = json_decode(select_query('gluu/oxd/gluu_scopes'),true);
$gluu_config                = json_decode(select_query('gluu/oxd/gluu_config'),true);
$gluu_acr                   = json_decode(select_query('gluu/oxd/gluu_acr'),true);
$gluu_auth_type             = select_query('gluu/oxd/gluu_auth_type');
$gluu_send_user_check       = select_query('gluu/oxd/gluu_send_user_check');
$gluu_provider              = select_query('gluu/oxd/gluu_provider');
$gluu_custom_logout         = select_query('gluu/oxd/gluu_custom_logout');
$gluu_new_roles             = json_decode(select_query('gluu/oxd/gluu_new_role'));
$gluu_users_can_register    = select_query('gluu/oxd/gluu_users_can_register');

if(Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    ?>
    <script>
        location.reload();
    </script>
    <?php
}

$this->gluuoxd_openid_login_validate();
if($this->gluu_is_port_working()) {
    if ($gluu_send_user_check && $gluu_oxd_id) {
        header("Location: " . $this->gluuoxd_get_auth_url());
        exit;
    } else if (!$gluu_send_user_check && $gluu_oxd_id) {
        ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="application/javascript">
            var jQuery = $.noConflict();
            jQuery(document).ready(function () {
                jQuery(".account-login").before("<br/><div><label><h3><input type='radio' name='radio' id='OpenID' value='Yes' style='margin-right: 7px'/>Login by OpenID Provider </h3></label>" +
                    "<br/><label><h3><input type='radio' name='radio' id='base' value='No' style='margin-right: 7px'/>Show login form</h3></label></div>");
                jQuery(".account-login").before('<div><a href="<?php echo $this->gluuoxd_get_auth_url();?>" style="background:green; color:#ffffff; font-size: 17px;padding: 15px" class="button" id="gluu_login">Login by OpenID Provider</a></div>');

                jQuery(".account-login").hide();
                jQuery('input:radio[name="radio"]').change(
                    function () {
                        if (jQuery(this).is(':checked') && jQuery(this).val() == 'Yes') {
                            jQuery('#gluu_login').show();
                            jQuery('.account-login').hide();
                        } else {
                            jQuery('#gluu_login').hide();
                            jQuery('.account-login').show();
                        }
                    });
                jQuery('#OpenID').attr('checked', true);
            });
        </script>
        <?php
    }
}

