<?php
function select_query($action){
    $result = Mage::getStoreConfig($action);
    return $result;
}

$gluu_oxd_id_admin          = select_query('gluu/oxd/gluu_oxd_id_admin');
$get_scopes                 = json_decode(select_query('gluu/oxd/gluu_scopes'),true);
$gluu_config                = json_decode(select_query('gluu/oxd/gluu_config'),true);
$gluu_acr                   = json_decode(select_query('gluu/oxd/gluu_acr'),true);
$gluu_auth_type             = select_query('gluu/oxd/gluu_auth_type');
$gluu_send_admin_check      = select_query('gluu/oxd/gluu_send_admin_check');
$gluu_provider              = select_query('gluu/oxd/gluu_provider');
$gluu_custom_logout         = select_query('gluu/oxd/gluu_custom_logout');
$gluu_new_roles             = json_decode(select_query('gluu/oxd/gluu_new_role'));
$gluu_users_can_register    = select_query('gluu/oxd/gluu_users_can_register');

$this->gluuoxd_openid_login_validate_admin();
if($this->gluu_is_port_working()) {
    if($gluu_send_admin_check && $gluu_oxd_id_admin) {
        header("Location: ".$this->gluuoxd_get_auth_url_admin());
        exit;
    }
    elseif(!$gluu_send_admin_check && $gluu_oxd_id_admin) {

        ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="application/javascript">
            var jQuery = $.noConflict();
            jQuery(document).ready(function () {
                jQuery(".login-form").attr('id', 'core_form');
                jQuery("#core_form").before("<div class='login-form' style='padding-bottom: 5px !important;'><label><h3><input type='radio' name='radio' id='OpenID' value='Yes' style='margin-right: 7px'/>Login by OpenID Provider </h3></label>" +
                    "<label><h3><input type='radio' name='radio' id='base' value='No' style='margin-right: 7px'/>Show login form</h3></label></div>");
                jQuery("#core_form").before('<div id="openid_form" class="login-form"><a href="<?php echo $this->gluuoxd_get_auth_url_admin();?>"  style="text-decoration:none; cursor: pointer;background:green; color:#ffffff; font-size: 17px;padding: 15px" class="button" id="gluu_login">Login by OpenID Provider</a></div>');

                jQuery("#core_form").hide();
                jQuery('input:radio[name="radio"]').change(
                    function () {
                        if (jQuery(this).is(':checked') && jQuery(this).val() == 'Yes') {
                            jQuery('#openid_form').show();
                            jQuery('#core_form').hide();
                        } else {
                            jQuery('#openid_form').hide();
                            jQuery('#core_form').show();
                        }
                    });
                jQuery('#OpenID').attr('checked', true);
            });
        </script>
        <?php
    }
}




